### ISSUE TITLE
[FR] Option to exclude folders

### ISSUE THREAD

**Issue by tricolon** [jillro/obsidian-cards-view-plugin#5]
It would be great if users could exclude certain folders (like the template folder) from the view in the plugin settings!

**Comment by Rulerchase5** [comment]
Strongly agree. I said in my own "issue" that I only have one frustration with this plugin, and that's true. This issue is not frustrating for me, but would make the plugin even more incredibly helpful.

**Comment by tu2-atmanand** [comment]
> Another approach to solve this might be something like a folder filter next to the search bar of the cards view UI. The possibility to show specific folders exclusively and quickly switch between the filtered directories would be very helpful.

Thats a great suggestion, for the users who are coming from Google Notes and all, functionalities like this will give them a great customization and filtering power. Also, the main FR to exclude is also very important, so that users can set all the folders in the setting to be completely excluded from searching at all.

For now, the following PR has done some great job in providing a very important feature, which will also going to help a lot, but the above discussed functionalities are also essential along with this : #12

**Comment by tu2-atmanand** [comment]
Hii guys !

I have integrated this feature as well in my version of this plugin, which will also be released on the Obsidian plugin marketplace. read more about it : https://github.com/jillro/obsidian-cards-view-plugin/pull/27#issuecomment-2526272260
